# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d2423cfb737159e4b5f21abeccc53abff5211943a3dd2cdedf54c542b51065b911bb75b0c43b0cc9345fb7b3ebc786fdb0752569d7ab53036a94312393579d4

test:
  secret_key_base: 8a8a9f27e7a622b5bf4c0e74af5a2ff95df4760ec87a57b737d3093f5f6779269e916c0037467023f3c65128a3fbcc0d3f755db2fc85353ea6c96ac8d83d141e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
